### ISSUE TITLE
Improve Pn_Debug performance

### ISSUE THREAD

**Issue by deshack** [Mte90/WordPress-Plugin-Boilerplate-Powered#11]
You can improve Pn_Debug class performances a little bit by switching the capabilities and `WP_DEBUG` checks.

Current check:

```php
if ( ! current_user_can( 'manage_options' ) || ! WP_DEBUG )
    return;
```

Since `WP_DEBUG` is a constant, thus replaced with its own value at compile time, you can short circuit the conditional and avoid a function call when WP_DEBUG is false.

```php
if ( ! WP_DEBUG || ! current_user_can( 'manage_options' ) )
    return;
```

**Comment by Mte90** [comment]
+1
