### ISSUE TITLE
Cron example

### ISSUE THREAD

**Issue by Mte90** [Mte90/WordPress-Plugin-Boilerplate-Powered#21]

**Comment by bigmike7801** [comment]
I'd be really interested in seeing this!

**Comment by Mte90** [comment]
i'm searching of a library or class to integrate but i'ive founded something very cool :-/

**Comment by bigmike7801** [comment]
Any update on this? I'm having issues setting up a cron using this boilerplate.

**Comment by Mte90** [comment]
I'm searching a library for simplify the cron in WordPress without success.
What is the problem of your code?

**Comment by bigmike7801** [comment]
I'm trying to figure out how to schedule/run a cron within the plugin_admin portion. I solved half the problem by modifying to `if ( is_admin() || defined( 'DOING_CRON' )`

**Comment by Mte90** [comment]
Is the correct way, the comment in that part explain to remove the ajax part if you need the ajax support.

**Comment by bigmike7801** [comment]
What comment are you talking about?

**Comment by Mte90** [comment]
Here: https://github.com/Mte90/WordPress-Plugin-Boilerplate-Powered/blob/master/plugin-name%2Fplugin-name.php#L128

**Comment by bigmike7801** [comment]
I think I've solved my issue to moving cron jobs to the "public" scope rather than the "admin".

**Comment by Mte90** [comment]
https://gist.github.com/brutalenemy666/f05a038eba6519a3f86a
Maybe I can improve that class...

**Comment by Mte90** [comment]
https://github.com/Mte90/CronPlus tadah!
