### ISSUE TITLE
Pluggable Functions

### ISSUE THREAD

**Issue by overclokk** [Mte90/WordPress-Plugin-Boilerplate-Powered#27]
Sarebbe utile mettere un controllo per le funzioni in caso vengano utilizzate in altri plugin, ci stavo pensando mentre facevo un controllo sulle funzioni per il multilingua che ho quindi messo in una if per evitare eventuali conflitti con altri plugin sviluppati usando il tuo codice, un po' il problema che si è creato con composer.

**Comment by Mte90** [comment]
basta dargli un prefisso alle funzioni, cosa che il generatore lo fà per il file template ed altri ma effettivamente in language non c'è nessun check.

**Comment by overclokk** [comment]
Si, infatti era solo per le funzioni che non vengono rinominate.
