### ISSUE TITLE
Retrieve Optios Page values

### ISSUE THREAD

**Issue by mimothemes** [Mte90/WordPress-Plugin-Boilerplate-Powered#28]
Hi, congrats for this great plugin starter, i am using it and cannot find the way to get the demo options page values.

Do i need to code my own function to get the values or is it included? I cannot find it.

Thank you very much!

**Comment by Mte90** [comment]
Thanks!
i use get_options() like here https://github.com/WebDevStudios/CMB2/wiki/Basic-Usage

**Comment by mimothemes** [comment]
Hi, thank you for the help.

Do you mean get_option() ?¿? So if you can tell me how i can get this option, I have all settings page intact, only touched the color picker in Settings 2 page as :+1: 


    <div id="tabs-2" class="wrap">
	    <?php
	    $cmb = new_cmb2_box( array(
		'id' => $this->plugin_slug . '_options-second',
		'hookup' => false,
		'show_on' => array( 'key' => 'options-page', 'value' => array( $this->plugin_slug ), ),
		'show_names' => true,
		    ) );
	    $cmb->add_field( array(
		'name' => __( 'Text', $this->plugin_slug ),
		'desc' => __( 'field description (optional)', $this->plugin_slug ),
		'id' => $this->plugin_slug . '_text-second',
		'type' => 'text',
		'default' => 'Default Text',
	    ) );
	    $cmb->add_field( array(
		'name' => __( 'Color Picker', $this->plugin_slug ),
		'desc' => __( 'field description (optional)', $this->plugin_slug ),
		'id' => $this->plugin_slug . 'map_sea',
		'type' => 'colorpicker',
		'default' => '#bada55',
	    ) );

	    cmb2_metabox_form( $this->plugin_slug . '_options-second', $this->plugin_slug . '-settings-second' );
	    ?>

	    
	</div>



My plugin_slug is 'mm_' , so how can i retrive this option? 

I am using: 

    $mm_map_sea = get_option('mm_map_sea','#000000');


with no luck

**Comment by Mte90** [comment]
CMB save the value on array when used as a settings panel (check their wiki).
To get the value you need to do (check the cmb2_metabox_form function):
```
$options = get_option( $this->plugin_slug . '-settings-second' );
```

**Comment by mimothemes** [comment]
Thank you very much for your help, if i do:

$options = get_option( $this->plugin_slug . '-settings-second' );

I thought it was then $options['mm_map_sea'] to get the value , but this is not working so i do:


var_dump($options);

i get:

bool(false)



Sorry i am a beginner coding at this level and i don't get this. I am used to CMB2, i use it long time ago, but i may be missing something at this point :)

**Comment by Mte90** [comment]
if you are calling $this outside the class-plugin-name.php file plugin_slug not exist.
try with:
```
$options = get_option( 'mm_-settings-second' );
```

**Comment by mimothemes** [comment]
I am calling it inside class-plugin-name.php file, inside a public function i made. I am also new to Classes sorry, for sure i am doing something wrong.

With your last code it works perfectly.

Thank you very much!!
Best regards

**Comment by Mte90** [comment]
No problem :-)
i suggest to you to read the docs of the library or the wiki of the boilerplate for other info
