### ISSUE TITLE
Parse error: syntax error, unexpected ... runtime-created function on line 1

### ISSUE THREAD

**Issue by overclokk** [Mte90/WordPress-Plugin-Boilerplate-Powered#30]
Ciao Daniele,
problema riscontrato con la funzione register_string per il supporto al multilingua e il plugin Ceceppa
```
Parse error: syntax error, unexpected ',', expecting '&' or variable (T_VARIABLE) in E:\xampp\htdocs\italystrap\wp-content\plugins\italy-cookie-choices\includes\functions-italy-cookie-choices-lang.php(57) : runtime-created function on line 1
```

Mi si presenta se uso più di 3 o 4 volte la funzione mentre sanitizzo gli input, se la uso solo meno di 3 o 4 non si presenta l'errore, visto che il mio plugin prevede PHP >= 5.3 ho usato una funzione anonima:

```
add_filter( 'cml_my_translations', function ( $groups, $plugin_name_human_format ){
	$plugin_name_human_format_replaced = str_replace( ' ', '-', $plugin_name_human_format );
	CMLTranslations:add( $string_name, $value, $plugin_name_human_format );
	$groups[$plugin_name_human_format_replaced] = $plugin_name_human_format;
	return $groups;
} );
```

Se vuoi provarlo anche tu puoi usare la 2.3.4 https://github.com/ItalyCookieChoices/italy-cookie-choices/releases

Altra cosa strana è che non vedo le stringhe da tradurre in "le mie traduzioni"

**Comment by Mte90** [comment]
ho dovuto usare create_function per php 5.2 ma se hai risolto meglio cosí.
per la questione ceceppa é meglio chiedere ad alessandro che io non ho fatto altro che studiarmi la suadocumentazione.

**Comment by overclokk** [comment]
Si, infatti immaginavo, te l'ho voluto far presente nel caso altri avessero lo stesso problema.

Ora sento anche da Alessandro
