### ISSUE TITLE
I used yeoman but ...

### ISSUE THREAD

**Issue by MercedesAMG1** [Mte90/WordPress-Plugin-Boilerplate-Powered#32]
It created a *.json file but did not create and files what so ever 

When I created a directory under wp-content/plugins

yeoman generator complained about a directory being there

Not sure what I am doing wrong

There is an Error

ENOENT, no such file or directory then it calls for a plugin directory which is not being created

**Comment by MercedesAMG1** [comment]
![screenshot 2015-08-05 02 43 20](https://cloud.githubusercontent.com/assets/5505432/9081756/5a1e31f4-3b1c-11e5-89cb-0bb882a6ab25.png)

**Comment by Mte90** [comment]
The yeoman generator works only on Unix because use sed for clean the files, is not supported on windows.

**Comment by MercedesAMG1** [comment]
so what I need to use it on a linux box

**Comment by MercedesAMG1** [comment]
or should work on a mac too ...

**Comment by Mte90** [comment]
The generator yes, actually I don't have found a workaround for Windows but sed exist in linux and mac.
