### ISSUE TITLE
call_user_func_array() expects parameter 1 to be a valid callback

### ISSUE THREAD

**Issue by MercedesAMG1** [Mte90/WordPress-Plugin-Boilerplate-Powered#33]
Got the generator to work on a mac and was able to genrate full set of files

Finally got it loaded into a localhost wamp install

Was able to successfully install plugin

Got the following two(2) errors when trying to activate plugin
(1)
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'My_First_Try_Admin' not found in C:\wamp\www\website.com\wp-includes\plugin.php on line 496
(2)
 Fatal error: Class 'Plugin_Name' not found in C:\wamp\www\website.com\wp-content\plugins\my-first-try\includes\widgets\sample.php on line 8

**Comment by MercedesAMG1** [comment]
In Error (1) wordpress is complaining about something
Error (2) may be because of error(1)
Not sure what to do or where to fix

**Comment by MercedesAMG1** [comment]
I figured it out

Where it says to change the wording "Plugin_Name"
I have to change that to the name of the plugin

I just kept fixing the errors as they showed up and all seems to fine with this issue.

@TODO means there is something for the coder todo

**Comment by Mte90** [comment]
Uhm okay, you found a bug :-)
But the correct place for problems of the generator is the repo of the generator https://github.com/Mte90/generator-wp-plugin-boilerplate-powered/

**Comment by Mte90** [comment]
ok i've released a new version of boilerplate and generator with bugfix :-)
