### ISSUE TITLE
Text at top of my-first-try.php plugin file

### ISSUE THREAD

**Issue by MercedesAMG1** [Mte90/WordPress-Plugin-Boilerplate-Powered#34]
This is the exact code in the header comments on the main my-first-try.php file as generated by YO
 with this in the file my plugin would not install and as a consequence not activate
--------------------------------------------------------------
 * @wordpress-plugin
 * My First Try:       @TODO
 * Plugin URI:        @TODO
 * Description:       @TODO
 * Version:           0.0.1
 * Author:            Peter
 
 --------------------------------------------------------------
 This is what I changed it to to be able to load it into my wordpress site
I was then able to install and activate
 ------------------------------------------------------------
 * @wordpress-plugin
 * Plugin Name:       My First Try       
 * Plugin URI:          www.com
 * Description:         a bunch of stuff
 * Version:               0.0.1
 * Author:                Peter

OR
Am I doing something wrong

I just answered the YO Generator questions

**Comment by MercedesAMG1** [comment]
I figured it out

@TODO Means to change stuff so it works

**Comment by Mte90** [comment]
Uhm okay, you found a bug :-)
But the correct place for problems of the generator is the repo of the generator https://github.com/Mte90/generator-wp-plugin-boilerplate-powered/
