### ISSUE TITLE
Fix per i metodi del plugin ceceppa multilingua

### ISSUE THREAD

**Issue by overclokk** [Mte90/WordPress-Plugin-Boilerplate-Powered#42]
Ciao Daniele,
ho riscontrato alcuni problemi con il plugin Ceceppa a cui ho trovato anche la soluzione provvisoria che ti passo, il problema era che non venivano stampate le traduzioni nel front-end e non venivano neanche registrate sul DB, visto che ci sono diverse modifiche prima di passarti il file preferisco indicartele qui:
Comincio dalla fine:
Riga 102
```php
return CMLTranslations::get( CMLLanguage::get_current_id(), strtolower( $string_name ), str_replace( ' ', '-', $plugin_name_human_format, $true ) );
```
Ho aggiunto strlower perchè viene usato nel metodo per registrare la stringa nel db (fatto vari var_dump), in questo modo viene regolarmente stampata la stringa nel front-end (nel back-end nessun problema) visto che è case sensitive.

Riga 81
```php
CMLTranslations::delete( $plugin_name_human_format );
```
Con il metodo CMLTranslations::add e CMLTranslations:get usi `$plugin_name_human_format` non `$plugin_name_human_format_replaced`.

E ora veniamo alla parte grossa, alla riga 52 sfrutti il filtro `cml_my_translations` che però al salvataggio delle opzioni (nel mio caso il plugin dei cookie) non viene eseguito e quindi ciccia, non salva le stringhe, poi hai dimenticato i : nel metodo e manca anche la funzione str_replace sulla variabile `$plugin_name_human_format`, qui il metodo corretto:
```php
CMLTranslations::add( $string_name, $value, str_replace( ' ', '-', $plugin_name_human_format ) );
```
Penso sia meglio però fare il check se esiste la classe e non il filtro, ma non ho ancora provato se funziona anche così.

Ora rimane solo dove mettere la lista delle stringhe nel back-end, al momento l'unica soluzione è creare una funzione esterna e appendersi al filtro:
```php
function cml_icc_strings( $groups ) {
  $groups[ "Italy-Cookie-Choices" ] = "Italy Cookie Choices";
  return $groups;
}
add_filter( 'cml_my_translations', 'cml_icc_strings' );
```
Però rimane il problema di passare il parametro del nome del plugin, questa era solo una funzione per fare un test che ha funzionato.
Intanto sistemo meglio il mio file, vedi tu cosa fare.

**Comment by Mte90** [comment]
fammi avere il file con le modifiche io intanto vedo se @ceceppa ha qualche consiglio.

**Comment by overclokk** [comment]
Ok, appena è pronto te lo passo qui.

**Comment by overclokk** [comment]
Eccolo https://github.com/ItalyCookieChoices/italy-cookie-choices/blob/master/includes/functions-italy-cookie-choices-lang.php
In questo modo a me funziona senza errori.

**Comment by Mte90** [comment]
ho implementato il grosso ma per la parte specifica per cecepa preferisco sentire @ceceppa

**Comment by overclokk** [comment]
Ok, tienimi informato quando hai qualcosa.
