### ISSUE TITLE
WordPress_Requirement::getWordPressVersion() is not defined

### ISSUE THREAD

**Issue by deshack** [Mte90/WordPress-Plugin-Boilerplate-Powered#9]
File: `/public/includes/requirements.php'

Called by: `WordPress_Requirement::message()`

The method `WordPress_Requirement::getWordPressVersion()` is called, but not defined.

**Comment by Mte90** [comment]
fixed with https://github.com/Mte90/WordPress-Plugin-Boilerplate-Powered/commit/6bf946eb32b42f4a6c0ab283c3373b66cab4ce64
